'use client';

import { useCallback } from 'react';
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from '@/components/ui/card';
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@/components/ui/table';
import { Button } from '@/components/ui/button';
import { generatePayslip } from '@/lib/utils/payslipGenerator';
import { toast } from 'sonner';

interface SalaryPaymentRow {
  _id: string;
  amount: number;
  periodMonth: number;
  periodYear: number;
  payDate: string;
  status: string;
}

interface EmployeePayslipsProps {
  payments: SalaryPaymentRow[];
}

const MONTH_LABELS = [
  '',
  'January',
  'February',
  'March',
  'April',
  'May',
  'June',
  'July',
  'August',
  'September',
  'October',
  'November',
  'December',
];

export function EmployeePayslips({ payments }: EmployeePayslipsProps) {
  // In this simple implementation we don't include the employee name in each payment row,
  // so we rely on a generic placeholder in the PDF. This can be enhanced later to include
  // the actual employee name if needed.
  const downloadPayslip = useCallback(
    (payment: SalaryPaymentRow) => {
      try {
        const paymentDateIso = new Date(payment.payDate).toISOString().slice(0, 10);

        const html = generatePayslip({
          employeeName: 'Employee',
          paymentDate: paymentDateIso,
          amountINR: payment.amount,
        });

        const win = window.open('', '_blank');
        if (!win) {
          toast.error('Popup blocked. Please allow popups to download the payslip.');
          return;
        }
        win.document.write(html);
        win.document.close();
        // Give the browser a moment to render, then trigger print so the user can save as PDF.
        win.focus();
        setTimeout(() => {
          win.print();
        }, 500);
      } catch (error: any) {
        console.error('Failed to generate payslip:', error);
        toast.error('Failed to generate payslip');
      }
    },
    []
  );

  return (
    <Card>
      <CardHeader>
        <CardTitle>Your Payslips</CardTitle>
        <CardDescription>
          Download formal payslips generated by ClassyEndeavors for your salary payments.
        </CardDescription>
      </CardHeader>
      <CardContent>
        {payments.length === 0 ? (
          <p className="text-sm text-muted-foreground text-center py-8">
            You do not have any recorded salary payments yet.
          </p>
        ) : (
          <div className="overflow-x-auto">
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Period</TableHead>
                  <TableHead>Pay date</TableHead>
                  <TableHead>Amount (INR)</TableHead>
                  <TableHead>Status</TableHead>
                  <TableHead className="text-right">Actions</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {payments.map((payment) => {
                  const monthLabel = MONTH_LABELS[payment.periodMonth] || payment.periodMonth;
                  const payDateFormatted = new Date(payment.payDate).toLocaleDateString(
                    'en-IN',
                    {
                      day: '2-digit',
                      month: 'short',
                      year: 'numeric',
                    }
                  );

                  return (
                    <TableRow key={payment._id}>
                      <TableCell>
                        {monthLabel} {payment.periodYear}
                      </TableCell>
                      <TableCell>{payDateFormatted}</TableCell>
                      <TableCell>₹ {payment.amount.toLocaleString('en-IN')}</TableCell>
                      <TableCell className="capitalize">{payment.status.toLowerCase()}</TableCell>
                      <TableCell className="text-right">
                        <Button size="sm" variant="outline" onClick={() => downloadPayslip(payment)}>
                          Download PDF
                        </Button>
                      </TableCell>
                    </TableRow>
                  );
                })}
              </TableBody>
            </Table>
          </div>
        )}
      </CardContent>
    </Card>
  );
}

